### ISSUE TITLE
C++ Implementation

### ISSUE THREAD

**Issue by saikishor** [kylc/optik#3]
Hello!

I'm interested to know if you have a C++ implementation of this super cool IK library or if are you planning to implement it in near future.

**Comment by kylc** [comment]
Hi @saikishor, thanks for your interest in the project. I have some interest in developing C++ bindings for this library, but no concrete plans. Stay tuned!

**Comment by saikishor** [comment]
Hello @kylc!

Thank you for the response. Sure, I will be waiting for the C++ implementation. Thanks.

Best Regards,
Sai

**Comment by kylc** [comment]
C++ bindings are now available on the `master` branch. Take a look at the README, and feel free to post any feedback.

**Comment by saikishor** [comment]
Thank you so much!
